import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import test from 'node:test'

const dir = dirname(fileURLToPath(import.meta.url))
const root = join(dir, '../..')

function read(rel: string): string {
  return readFileSync(join(root, rel), 'utf8')
}

test('host and query core do not switch on vendor names', () => {
  const host = read('src/host.ts')
  const query = read('src/core/query.ts')
  assert.doesNotMatch(host, /if\s*\(.*provider\s*===\s*['"]tencent['"]/)
  assert.doesNotMatch(host, /if\s*\(.*provider\s*===\s*['"]aliyun['"]/)
  assert.doesNotMatch(query, /tencent\s*\|\s*aliyun/)
  assert.match(host, /settings\.register\('cloud-infra'/)
  assert.match(host, /cloud_infra_query/)
})

test('client settings card is schema-driven and uses key cloud-infra', () => {
  const client = read('src/client.js')
  assert.match(client, /key:\s*"cloud-infra"/)
  assert.match(client, /provider\.fields/)
  assert.doesNotMatch(client, /if\s*\(.*===\s*['"]tencent['"]/)
  assert.match(client, /confirm === "always"/)
  assert.match(client, /ci-row/)
  assert.match(client, /item\.columns/)
  assert.match(client, /上一页/)
  assert.match(client, /请输入域名关键字/)
})

test('ConfigCard credential rows share a host-isolated label+input grid (g1.1 g1.2 g1.3)', () => {
  const client = read('src/client.js')
  assert.match(client, /className:\s*"ci-cfg-row"/)
  assert.match(client, /\(provider\.fields\s*\|\|\s*\[\]\)\.map\(\(field\)\s*=>\s*h\("div",\s*\{\s*key:\s*field\.key,\s*className:\s*"ci-cfg-row"/)
  assert.match(client, /className:\s*"ci-cfg-row"[\s\S]{0,120}htmlFor:\s*"ci-max"[\s\S]{0,40}每页条数/)
  assert.match(client, /\.ci-cfg-row\{[^}]*display:grid/)
  assert.match(client, /\.ci-cfg-row\{[^}]*grid-template-columns:9\.5em 1fr/)
  assert.match(client, /\.ci-cfg-row\{[^}]*align-items:center/)
  assert.match(client, /\.ci-cfg-row\{[^}]*box-sizing:border-box/)
  assert.match(client, /\.ci-cfg-row\{[^}]*float:none/)
  assert.match(client, /\.ci-cfg-row\{[^}]*position:static/)
  assert.match(client, /\.ci-cfg-row>label\{[^}]*float:none/)
  assert.match(client, /\.ci-cfg-row>label\{[^}]*position:static/)
  assert.match(client, /\.ci-cfg-row>label\{[^}]*vertical-align:middle/)
  assert.match(client, /\.ci-cfg-row>input\[type=text\][^}]*width:100%/)
  assert.match(client, /\.ci-cfg-row>input\[type=text\][^}]*float:none/)
  assert.match(client, /\.ci-cfg-row>input\[type=text\][^}]*position:static/)
  const card = client.slice(client.indexOf('function ConfigCard()'))
  assert.match(card, /function ConfigCard\(/)
  assert.match(card, /h\("label",\s*\{\s*className:\s*"ci-cfg-src"\s*\},[\s\S]*?checked:\s*bucket\.enabled[\s\S]*?"启用"/)
  assert.doesNotMatch(card, /className:\s*"ci-cfg-row"[\s\S]{0,40}checked:\s*bucket\.enabled/)
  assert.match(card, /h\("label",\s*\{\s*className:\s*"ci-cfg-src"\s*\},[\s\S]*?draft\.skipConfirm[\s\S]*?写操作免确认/)
  assert.doesNotMatch(card, /className:\s*"ci-cfg-row"[\s\S]{0,80}draft\.skipConfirm/)
})

test('ConfigCard save still omits empty secrets so stored keys stay (g2.2)', () => {
  const client = read('src/client.js')
  assert.match(client, /placeholder:\s*bucket\.configured\s*\?\s*"已保存，留空则保持原值"/)
  assert.match(client, /if\s*\(String\(value\s*\|\|\s*""\)\.trim\(\)\)\s*next\[key\]\s*=\s*String\(value\)\.trim\(\)/)
  assert.match(client, /api\("config",\s*\{\s*save:\s*true/)
  assert.match(client, /className:\s*"ci-cfg-disc"/)
  assert.match(client, /className:\s*"ci-cfg-save"/)
})

test('product module list is a vertical checkbox stack with truncated titles', () => {
  const client = read('src/client.js')
  assert.match(client, /"产品模块"/)
  assert.match(client, /className: "ci-cfg-mod-row"/)
  assert.match(client, /\.ci-cfg-mod-row\{display:flex;align-items:center/)
  assert.match(client, /\.ci-cfg-mod-title\{overflow:hidden;text-overflow:ellipsis;white-space:nowrap/)
  assert.match(client, /draft\.modules\[module\.id\] !== false/)
  assert.match(client, /module\.title \|\| module\.id/)
  assert.doesNotMatch(client, /className: "ci-cfg-src"[\s\S]{0,120}modules\.map/)
})

test('product module list scrolls inside a max-height box and keeps footer outside', () => {
  const client = read('src/client.js')
  assert.match(client, /\.ci-cfg-mod-list\{max-height:196px;overflow-y:auto/)
  assert.doesNotMatch(client, /\.ci-cfg-mod-list\{[^}]*min-height/)
  assert.doesNotMatch(client, /\.ci-cfg-mod-list\{[^}]*overflow-y:scroll/)
  const listAt = client.indexOf('className: "ci-cfg-mod-list"')
  const footAt = client.indexOf('className: "ci-cfg-ft"')
  assert.ok(listAt > 0 && footAt > listAt, 'footer stays after the module list')
  assert.match(client, /放弃修改/)
  assert.match(client, /className: "ci-cfg-save"/)
  assert.match(client, /setDraft\(saved\)/)
})

test('product module filter is local and does not clear checked draft.modules', () => {
  const client = read('src/client.js')
  assert.match(client, /className: "ci-cfg-mod-q"/)
  assert.match(client, /placeholder: "筛选模块名称"/)
  assert.match(client, /onChange: \(e\) => setModQ\(e\.target\.value\)/)
  assert.match(client, /没有匹配的模块/)
  assert.match(client, /已启用 \$\{enabledModCount\} \/ \$\{modules\.length\}/)
  assert.match(client, /筛选中/)
  assert.match(client, /function matchModule/)
  assert.match(client, /title\.includes\(needle\) \|\| id\.includes\(needle\)/)
  const filterChange = client.slice(client.indexOf('placeholder: "筛选模块名称"'), client.indexOf('className: "ci-cfg-mod-list"'))
  assert.doesNotMatch(filterChange, /api\(/)
})

test('matchModule filters by title or id without dropping other checked modules', () => {
  const src = read('src/client.js')
  const start = src.indexOf('function matchModule')
  assert.ok(start >= 0)
  const end = src.indexOf('\n    function configToDraft', start)
  const fn = new Function('module', 'q', `${src.slice(start, end)}\nreturn matchModule(module, q)`) as (
    module: { id: string; title?: string },
    q: string,
  ) => boolean
  assert.equal(fn({ id: 'tencent.domain', title: '腾讯云域名' }, ''), true)
  assert.equal(fn({ id: 'tencent.domain', title: '腾讯云域名' }, '域名'), true)
  assert.equal(fn({ id: 'tencent.domain', title: '腾讯云域名' }, 'TENCENT'), true)
  assert.equal(fn({ id: 'aliyun.dns', title: '阿里云解析' }, '域名'), false)
  assert.equal(fn({ id: 'aliyun.dns', title: '阿里云解析' }, '   '), true)
})

test('config contract stays modules Record and hides unimplemented entries', () => {
  const client = read('src/client.js')
  const host = read('src/host.ts')
  const store = read('src/core/config-store.ts')
  assert.match(client, /key:\s*"cloud-infra"/)
  assert.match(client, /m\.implemented !== false/)
  assert.match(client, /modules: draft\.modules/)
  assert.match(client, /modules\.length \? h\("div"/)
  assert.match(host, /settings\.register\('cloud-infra'/)
  assert.match(store, /modules: Record<string, boolean>/)
  assert.doesNotMatch(client, /if\s*\(.*===\s*['"]tencent['"]/)
})

test('settings card save/discard and single-or-many module cases stay wired', () => {
  const client = read('src/client.js')
  assert.match(client, /disabled: !dirty \|\| saving/)
  assert.match(client, /onClick: \(\) => setDraft\(saved\)/)
  assert.match(client, /onClick: save/)
  assert.match(client, /visibleModules\.map/)
  assert.match(client, /checked: draft\.modules\[module\.id\] !== false/)
  const listRule = client.match(/\.ci-cfg-mod-list\{[^}]+\}/)?.[0] || ''
  assert.match(listRule, /max-height:196px/)
  assert.doesNotMatch(listRule.replace(/max-height:\d+px/g, ''), /height:\d+px/)
  assert.doesNotMatch(listRule, /min-height/)
})

test('g1 client uses official DSH tokens without typo or light hex fills', () => {
  const client = read('src/client.js')
  assert.match(client, /--dsw-alias-brand-primary[);,\s]/)
  assert.match(client, /--dsw-alias-button-primary-fill/)
  assert.match(client, /--dsw-alias-state-success-primary/)
  assert.match(client, /--dsw-alias-state-warn-label/)
  assert.match(client, /--dsw-alias-state-error-primary/)
  assert.doesNotMatch(client, /brand-primary-new-colorprimary-new-color/)
  assert.doesNotMatch(client, /#2563eb|#fff\b|#ffffff\b/)
  assert.match(client, /\.ci-cfg\{[^}]*background:transparent/)
  assert.match(client, /details\.ci-cfg>summary\.ci-cfg-h\{[^}]*background:transparent/)
})

test('g2-g3 list chrome and in-card DetailView replace fullscreen drawer', () => {
  const client = read('src/client.js')
  assert.match(client, /域名解析/)
  assert.match(client, /ci-bar-count/)
  assert.match(client, /没有匹配「/)
  assert.match(client, /加载列表/)
  assert.match(client, /function DetailView/)
  assert.match(client, /ci-crumb/)
  assert.match(client, /ci-back/)
  assert.match(client, /返回/)
  assert.match(client, /加载详情/)
  assert.match(client, /没有解析记录/)
  assert.match(client, /onBack:\s*\(\)\s*=>\s*setSession\(null\)/)
  assert.doesNotMatch(client, /ci-overlay|ci-drawer|function Drawer\b/)
  assert.doesNotMatch(client, /2147483|86vh/)
})

test('g6 dbbrain stays in the chat card with type+region filters and tabs', () => {
  const client = read('src/client.js')
  assert.match(client, /kind === "dbbrain"/)
  assert.match(client, /实例管理/)
  assert.match(client, /全地域/)
  assert.match(client, /诊断优化/)
  assert.match(client, /function DbbrainDetailView/)
  assert.match(client, /function DbbrainTable/)
  assert.match(client, /异常诊断/)
  assert.match(client, /内存分析/)
  assert.match(client, /索引推荐/)
  assert.match(client, /session\.kill/)
  assert.match(client, /confirm === "always"/)
  assert.match(client, /实例 ID \/ 名称/)
  assert.match(client, /地域只在对话卡片里选，不进设置/)
  assert.match(client, /ap-shanghai-fsi/)
  assert.match(client, /ap-jakarta/)
  assert.match(client, /item\.hasReport/)
  assert.match(client, /canKillSession/)
  assert.match(client, /创建中断任务/)
  assert.match(client, /range: ""/)
  assert.match(client, /sessionId: row\.sessionId/)
  assert.doesNotMatch(client, /function hasReportTab/)
  assert.doesNotMatch(client, /sessionId: row\.sessionId,\s*host:/)
  assert.doesNotMatch(client, /ci-sidenav|实例概览|监控告警/)
  assert.doesNotMatch(client, /if\s*\(.*===\s*['"]tencent['"]/)
  const card = client.slice(client.indexOf('function ConfigCard()'))
  assert.doesNotMatch(card, /htmlFor:\s*"ci-.*region"/)
  assert.doesNotMatch(card, /className:\s*"ci-cfg-row"[\s\S]{0,80}地域/)
})

test('g4 lightweight form/confirm overlay and g5 skipConfirm live update', () => {
  const client = read('src/client.js')
  assert.match(client, /min\(400px,100%\)/)
  assert.match(client, /Escape/)
  assert.match(client, /e\.target === e\.currentTarget/)
  assert.match(client, /cloud-infra-config/)
  assert.match(client, /function publicErrorMessage/)
  assert.match(client, /写操作免确认（删除仍会确认）/)
  assert.match(client, /未保存/)
})

test('g6 host query tool hits dbbrain keywords without vendor branches', () => {
  const host = read('src/host.ts')
  const query = read('src/core/query.ts')
  assert.match(host, /kind=dbbrain/)
  assert.match(host, /慢SQL/)
  assert.match(host, /异常诊断/)
  assert.match(query, /kind === 'dbbrain'/)
  assert.doesNotMatch(host, /if\s*\(.*provider\s*===\s*['"]tencent['"]/)
})
